### ISSUE TITLE
PluginInstaller not found

### ISSUE THREAD

**Issue by DigiAngel** [roundcube/plugin-installer#16]
After doing an upgrade from 1.1.4 to 1.3.6 I'm getting the below with "php composer.phar install"
~~~
HP Fatal error:  Uncaught Error: Class 'Roundcube\Composer\PluginInstaller' not found in phar:///var/www/html/roundcubemail/composer.phar/src/Composer/Plugin/PluginManager.php:201
Stack trace:
#0 phar:///var/www/html/roundcubemail/composer.phar/src/Composer/Plugin/PluginManager.php(264): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage))
#1 phar:///var/www/html/roundcubemail/composer.phar/src/Composer/Plugin/PluginManager.php(76): Composer\Plugin\PluginManager->loadRepository(Object(Composer\Repository\InstalledFilesystemRepository))
#2 phar:///var/www/html/roundcubemail/composer.phar/src/Composer/Factory.php(384): Composer\Plugin\PluginManager->loadInstalledPlugins()
#3 phar:///var/www/html/roundcubemail/composer.phar/src/Composer/Factory.php(576): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), Array, false)
#4 phar:///var/www/html/roundcubemail/composer.phar/src/Composer/Console/Application.php(338): Composer\Factory::create(Object(Composer\IO\ConsoleIO), NULL, false)
# in phar:///var/www/html/roundcubemail/composer.phar/src/Composer/Plugin/PluginManager.php on line 201

Fatal error: Uncaught Error: Class 'Roundcube\Composer\PluginInstaller' not found in phar:///var/www/html/roundcubemail/composer.phar/src/Composer/Plugin/PluginManager.php:201
Stack trace:
#0 phar:///var/www/html/roundcubemail/composer.phar/src/Composer/Plugin/PluginManager.php(264): Composer\Plugin\PluginManager->registerPackage(Object(Composer\Package\CompletePackage))
#1 phar:///var/www/html/roundcubemail/composer.phar/src/Composer/Plugin/PluginManager.php(76): Composer\Plugin\PluginManager->loadRepository(Object(Composer\Repository\InstalledFilesystemRepository))
#2 phar:///var/www/html/roundcubemail/composer.phar/src/Composer/Factory.php(384): Composer\Plugin\PluginManager->loadInstalledPlugins()
#3 phar:///var/www/html/roundcubemail/composer.phar/src/Composer/Factory.php(576): Composer\Factory->createComposer(Object(Composer\IO\ConsoleIO), Array, false)
#4 phar:///var/www/html/roundcubemail/composer.phar/src/Composer/Console/Application.php(338): Composer\Factory::create(Object(Composer\IO\ConsoleIO), NULL, false)
# in phar:///var/www/html/roundcubemail/composer.phar/src/Composer/Plugin/PluginManager.php on line 201
~~~

maybe related?  [https://github.com/roundcube/plugin-installer/issues/1](url)  Anything I can do to troubleshoot this on my end?  Thank you.

**Comment by thomascube** [comment]
Maybe the migration of your local composer.json file failed for some reason. Please compare it with the intended version from https://github.com/roundcube/roundcubemail/blob/release-1.3/composer.json-dist

Also worth to try: remove your local composer.lock file and re-run `php composer.phar install`.

**Comment by DigiAngel** [comment]
Thank you..I will report my findings after testing.

**Comment by DigiAngel** [comment]
Here's the composer file I'm working with:
~~~
{
    "name": "roundcube/roundcubemail",
    "description": "The Roundcube Webmail suite",
    "license": "GPL-3.0+",
    "repositories": [
        {
            "type": "pear",
            "url": "http://pear.php.net/"
        },
        {
            "type": "composer",
            "url": "https://plugins.roundcube.net/"
        },
        {
            "type": "vcs",
            "url": "https://git.kolab.org/diffusion/PNL/php-net_ldap.git"
        }
    ],
    "require": {
        "php": ">=5.4.0",
        "roundcube/plugin-installer": "~0.1.6",
        "roundcube/carddav": "dev-master",
        "roundcube/filters": "dev-master",
        "patchwork/utf8": "~1.2.3",
        "pear/pear-core-minimal": "~1.10.1",
        "pear/net_socket": "~1.2.1",
        "pear/auth_sasl": "~1.1.0",
        "pear/net_idna2": "~0.2.0",
        "pear/mail_mime": "~1.10.0",
        "pear/net_smtp": "~1.7.1",
        "pear/crypt_gpg": "~1.6.0",
        "pear/net_sieve": "~1.4.0",
        "endroid/qr-code": "~1.6.5"
    },
    "require-dev": {
        "pear-pear.php.net/crypt_gpg": "*",
        "phpunit/phpunit": "*"
    },
    "suggest": {
        "pear-pear.php.net/net_ldap2": "~2.1.0 required for connecting to LDAP address books",
        "kolab/Net_LDAP3": "dev-master required for connecting to LDAP address books"
    },
    "minimum-stability": "dev"
}
~~~
I removed the composer.lock file, but same results alas.  And after looking, now i see why.  The dir:
~~~
/var/www/html/roundcubemail/vendor/roundcube
~~~
is empty :(  I followed the upgrade instructions, but it looks like:
~~~
 ./bin/installto.sh <TARGET-FOLDER>
~~~
wiped out that dir.  After manually copying the plugin-installer directory over, now I get:
~~~
Updating dependencies (including require-dev)                  
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package pear-pear.php.net/crypt_gpg could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
~~~

Heh...this migration/upgrade is not going well ;)  Any hints on what I'm doing wrong would be awesome thanks again for the help.

**Comment by DigiAngel** [comment]
Yea something is pretty broken here...looks like on Ubuntu 18 at least pear doesn't get installed into pear-pear.php:
~~~
rwxrwxrwx 1 www-data www-data  53 Dec 30  2015 crypt-gpg-pinentry -> ../pear-pear.php.net/Crypt_GPG/bin/crypt-gpg-pinentry
lrwxrwxrwx 1 root     root      36 May 26 07:38 generate_vcards -> ../sabre/vobject/bin/generate_vcards
lrwxrwxrwx 1 www-data www-data  34 Dec 23  2015 pear -> ../pear-pear.php.net/PEAR/bin/pear
lrwxrwxrwx 1 www-data www-data  37 Dec 23  2015 peardev -> ../pear-pear.php.net/PEAR/bin/peardev
lrwxrwxrwx 1 www-data www-data  34 Dec 23  2015 pecl -> ../pear-pear.php.net/PEAR/bin/pecl
~~~
These all point to a non-exsistant directory.  Still digging.

**Comment by DigiAngel** [comment]
Got crypt_gpg installed with using this info: [https://www.roundcubeforum.net/index.php/topic,23404.0.html](url).  Closing this out.
